name: verifier
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - torchmetrics
  - faiss-cpu
  - transformers
  - datasets
  - sentencepiece
  - openai
  - pydantic=2.8.2
  - rich
  - pip:
      - argparse
      - wandb
      - peft
      - accelerate
