QUERY_GENERATION_PROMPT = """You are using a search engine to answer the main query by iteratively searching the web. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search engine may not understand complex questions.

## Previous intermediate queries and answers
{trace}

## Task description
answer multi-hop questions

## Main query to answer
{question}

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else."""


INTERMEDIATE_ANSWER_GENERATION_PROMPT = """Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond “No relevant information found” if the documents do not contain useful information.

## Documents
{docs}

## Query
{query}

Respond with a concise answer only, do not explain yourself or output anything else."""


FINAL_ANSWER_GENERATION_PROMPT = """Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.

## Documents
{docs}

## Intermediate queries and answers
{trace}

## Task description
answer multi-hop questions

## Main query
{question}

Respond with an appropriate answer only, do not explain yourself or output anything else."""
